// Code generated by Prisma (prisma@1.23.2). DO NOT EDIT.
// Please don't change this file manually but run `prisma generate` to update it.
// For more information, please read the docs: https://www.prisma.io/docs/prisma-client/

import { DocumentNode } from "graphql";
import {
  makePrismaClientClass,
  BaseClientOptions,
  Model
} from "prisma-client-lib";
import { typeDefs } from "./prisma-schema";

export type AtLeastOne<T, U = { [K in keyof T]: Pick<T, K> }> = Partial<T> &
  U[keyof U];

export interface Exists {
  tutorial: (where?: TutorialWhereInput) => Promise<boolean>;
  user: (where?: UserWhereInput) => Promise<boolean>;
  userTutorial: (where?: UserTutorialWhereInput) => Promise<boolean>;
}

export interface Node {}

export type FragmentableArray<T> = Promise<Array<T>> & Fragmentable;

export interface Fragmentable {
  $fragment<T>(fragment: string | DocumentNode): Promise<T>;
}

export interface Prisma {
  $exists: Exists;
  $graphql: <T = any>(
    query: string,
    variables?: { [key: string]: any }
  ) => Promise<T>;

  /**
   * Queries
   */

  tutorial: (where: TutorialWhereUniqueInput) => TutorialPromise;
  tutorials: (
    args?: {
      where?: TutorialWhereInput;
      orderBy?: TutorialOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => FragmentableArray<Tutorial>;
  tutorialsConnection: (
    args?: {
      where?: TutorialWhereInput;
      orderBy?: TutorialOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => TutorialConnectionPromise;
  user: (where: UserWhereUniqueInput) => UserPromise;
  users: (
    args?: {
      where?: UserWhereInput;
      orderBy?: UserOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => FragmentableArray<User>;
  usersConnection: (
    args?: {
      where?: UserWhereInput;
      orderBy?: UserOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => UserConnectionPromise;
  userTutorial: (where: UserTutorialWhereUniqueInput) => UserTutorialPromise;
  userTutorials: (
    args?: {
      where?: UserTutorialWhereInput;
      orderBy?: UserTutorialOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => FragmentableArray<UserTutorial>;
  userTutorialsConnection: (
    args?: {
      where?: UserTutorialWhereInput;
      orderBy?: UserTutorialOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => UserTutorialConnectionPromise;
  node: (args: { id: ID_Output }) => Node;

  /**
   * Mutations
   */

  createTutorial: (data: TutorialCreateInput) => TutorialPromise;
  updateTutorial: (
    args: { data: TutorialUpdateInput; where: TutorialWhereUniqueInput }
  ) => TutorialPromise;
  updateManyTutorials: (
    args: { data: TutorialUpdateManyMutationInput; where?: TutorialWhereInput }
  ) => BatchPayloadPromise;
  upsertTutorial: (
    args: {
      where: TutorialWhereUniqueInput;
      create: TutorialCreateInput;
      update: TutorialUpdateInput;
    }
  ) => TutorialPromise;
  deleteTutorial: (where: TutorialWhereUniqueInput) => TutorialPromise;
  deleteManyTutorials: (where?: TutorialWhereInput) => BatchPayloadPromise;
  createUser: (data: UserCreateInput) => UserPromise;
  updateUser: (
    args: { data: UserUpdateInput; where: UserWhereUniqueInput }
  ) => UserPromise;
  updateManyUsers: (
    args: { data: UserUpdateManyMutationInput; where?: UserWhereInput }
  ) => BatchPayloadPromise;
  upsertUser: (
    args: {
      where: UserWhereUniqueInput;
      create: UserCreateInput;
      update: UserUpdateInput;
    }
  ) => UserPromise;
  deleteUser: (where: UserWhereUniqueInput) => UserPromise;
  deleteManyUsers: (where?: UserWhereInput) => BatchPayloadPromise;
  createUserTutorial: (data: UserTutorialCreateInput) => UserTutorialPromise;
  updateUserTutorial: (
    args: { data: UserTutorialUpdateInput; where: UserTutorialWhereUniqueInput }
  ) => UserTutorialPromise;
  updateManyUserTutorials: (
    args: {
      data: UserTutorialUpdateManyMutationInput;
      where?: UserTutorialWhereInput;
    }
  ) => BatchPayloadPromise;
  upsertUserTutorial: (
    args: {
      where: UserTutorialWhereUniqueInput;
      create: UserTutorialCreateInput;
      update: UserTutorialUpdateInput;
    }
  ) => UserTutorialPromise;
  deleteUserTutorial: (
    where: UserTutorialWhereUniqueInput
  ) => UserTutorialPromise;
  deleteManyUserTutorials: (
    where?: UserTutorialWhereInput
  ) => BatchPayloadPromise;

  /**
   * Subscriptions
   */

  $subscribe: Subscription;
}

export interface Subscription {
  tutorial: (
    where?: TutorialSubscriptionWhereInput
  ) => TutorialSubscriptionPayloadSubscription;
  user: (
    where?: UserSubscriptionWhereInput
  ) => UserSubscriptionPayloadSubscription;
  userTutorial: (
    where?: UserTutorialSubscriptionWhereInput
  ) => UserTutorialSubscriptionPayloadSubscription;
}

export interface ClientConstructor<T> {
  new (options?: BaseClientOptions): T;
}

/**
 * Types
 */

export type UserTutorialOrderByInput =
  | "id_ASC"
  | "id_DESC"
  | "createdAt_ASC"
  | "createdAt_DESC"
  | "updatedAt_ASC"
  | "updatedAt_DESC"
  | "upvoted_ASC"
  | "upvoted_DESC"
  | "bookmarked_ASC"
  | "bookmarked_DESC"
  | "currentChapter_ASC"
  | "currentChapter_DESC";

export type TutorialOrderByInput =
  | "id_ASC"
  | "id_DESC"
  | "createdAt_ASC"
  | "createdAt_DESC"
  | "updatedAt_ASC"
  | "updatedAt_DESC"
  | "name_ASC"
  | "name_DESC"
  | "gatsbyID_ASC"
  | "gatsbyID_DESC"
  | "numberofChapters_ASC"
  | "numberofChapters_DESC"
  | "numberofStudents_ASC"
  | "numberofStudents_DESC"
  | "upvotes_ASC"
  | "upvotes_DESC";

export type UserOrderByInput =
  | "id_ASC"
  | "id_DESC"
  | "createdAt_ASC"
  | "createdAt_DESC"
  | "updatedAt_ASC"
  | "updatedAt_DESC"
  | "name_ASC"
  | "name_DESC"
  | "email_ASC"
  | "email_DESC"
  | "githubHandle_ASC"
  | "githubHandle_DESC"
  | "githubUserId_ASC"
  | "githubUserId_DESC"
  | "avatarUrl_ASC"
  | "avatarUrl_DESC"
  | "bio_ASC"
  | "bio_DESC"
  | "contributor_ASC"
  | "contributor_DESC"
  | "expertise_ASC"
  | "expertise_DESC";

export type MutationType = "CREATED" | "UPDATED" | "DELETED";

export interface UserUpdateOneWithoutUserTutorialsInput {
  create?: UserCreateWithoutUserTutorialsInput;
  update?: UserUpdateWithoutUserTutorialsDataInput;
  upsert?: UserUpsertWithoutUserTutorialsInput;
  delete?: Boolean;
  disconnect?: Boolean;
  connect?: UserWhereUniqueInput;
}

export type TutorialWhereUniqueInput = AtLeastOne<{
  id: ID_Input;
  gatsbyID?: String;
}>;

export interface UserTutorialUpsertWithWhereUniqueWithoutTutorialInput {
  where: UserTutorialWhereUniqueInput;
  update: UserTutorialUpdateWithoutTutorialDataInput;
  create: UserTutorialCreateWithoutTutorialInput;
}

export interface UserTutorialWhereInput {
  id?: ID_Input;
  id_not?: ID_Input;
  id_in?: ID_Input[] | ID_Input;
  id_not_in?: ID_Input[] | ID_Input;
  id_lt?: ID_Input;
  id_lte?: ID_Input;
  id_gt?: ID_Input;
  id_gte?: ID_Input;
  id_contains?: ID_Input;
  id_not_contains?: ID_Input;
  id_starts_with?: ID_Input;
  id_not_starts_with?: ID_Input;
  id_ends_with?: ID_Input;
  id_not_ends_with?: ID_Input;
  createdAt?: DateTimeInput;
  createdAt_not?: DateTimeInput;
  createdAt_in?: DateTimeInput[] | DateTimeInput;
  createdAt_not_in?: DateTimeInput[] | DateTimeInput;
  createdAt_lt?: DateTimeInput;
  createdAt_lte?: DateTimeInput;
  createdAt_gt?: DateTimeInput;
  createdAt_gte?: DateTimeInput;
  updatedAt?: DateTimeInput;
  updatedAt_not?: DateTimeInput;
  updatedAt_in?: DateTimeInput[] | DateTimeInput;
  updatedAt_not_in?: DateTimeInput[] | DateTimeInput;
  updatedAt_lt?: DateTimeInput;
  updatedAt_lte?: DateTimeInput;
  updatedAt_gt?: DateTimeInput;
  updatedAt_gte?: DateTimeInput;
  user?: UserWhereInput;
  tutorial?: TutorialWhereInput;
  upvoted?: Boolean;
  upvoted_not?: Boolean;
  bookmarked?: Boolean;
  bookmarked_not?: Boolean;
  currentChapter?: Int;
  currentChapter_not?: Int;
  currentChapter_in?: Int[] | Int;
  currentChapter_not_in?: Int[] | Int;
  currentChapter_lt?: Int;
  currentChapter_lte?: Int;
  currentChapter_gt?: Int;
  currentChapter_gte?: Int;
  AND?: UserTutorialWhereInput[] | UserTutorialWhereInput;
  OR?: UserTutorialWhereInput[] | UserTutorialWhereInput;
  NOT?: UserTutorialWhereInput[] | UserTutorialWhereInput;
}

export interface UserTutorialCreateManyWithoutTutorialInput {
  create?:
    | UserTutorialCreateWithoutTutorialInput[]
    | UserTutorialCreateWithoutTutorialInput;
  connect?: UserTutorialWhereUniqueInput[] | UserTutorialWhereUniqueInput;
}

export interface UserTutorialCreateManyWithoutUserInput {
  create?:
    | UserTutorialCreateWithoutUserInput[]
    | UserTutorialCreateWithoutUserInput;
  connect?: UserTutorialWhereUniqueInput[] | UserTutorialWhereUniqueInput;
}

export interface UserTutorialCreateWithoutTutorialInput {
  user?: UserCreateOneWithoutUserTutorialsInput;
  upvoted?: Boolean;
  bookmarked?: Boolean;
  currentChapter?: Int;
}

export interface UserTutorialScalarWhereInput {
  id?: ID_Input;
  id_not?: ID_Input;
  id_in?: ID_Input[] | ID_Input;
  id_not_in?: ID_Input[] | ID_Input;
  id_lt?: ID_Input;
  id_lte?: ID_Input;
  id_gt?: ID_Input;
  id_gte?: ID_Input;
  id_contains?: ID_Input;
  id_not_contains?: ID_Input;
  id_starts_with?: ID_Input;
  id_not_starts_with?: ID_Input;
  id_ends_with?: ID_Input;
  id_not_ends_with?: ID_Input;
  createdAt?: DateTimeInput;
  createdAt_not?: DateTimeInput;
  createdAt_in?: DateTimeInput[] | DateTimeInput;
  createdAt_not_in?: DateTimeInput[] | DateTimeInput;
  createdAt_lt?: DateTimeInput;
  createdAt_lte?: DateTimeInput;
  createdAt_gt?: DateTimeInput;
  createdAt_gte?: DateTimeInput;
  updatedAt?: DateTimeInput;
  updatedAt_not?: DateTimeInput;
  updatedAt_in?: DateTimeInput[] | DateTimeInput;
  updatedAt_not_in?: DateTimeInput[] | DateTimeInput;
  updatedAt_lt?: DateTimeInput;
  updatedAt_lte?: DateTimeInput;
  updatedAt_gt?: DateTimeInput;
  updatedAt_gte?: DateTimeInput;
  upvoted?: Boolean;
  upvoted_not?: Boolean;
  bookmarked?: Boolean;
  bookmarked_not?: Boolean;
  currentChapter?: Int;
  currentChapter_not?: Int;
  currentChapter_in?: Int[] | Int;
  currentChapter_not_in?: Int[] | Int;
  currentChapter_lt?: Int;
  currentChapter_lte?: Int;
  currentChapter_gt?: Int;
  currentChapter_gte?: Int;
  AND?: UserTutorialScalarWhereInput[] | UserTutorialScalarWhereInput;
  OR?: UserTutorialScalarWhereInput[] | UserTutorialScalarWhereInput;
  NOT?: UserTutorialScalarWhereInput[] | UserTutorialScalarWhereInput;
}

export interface UserCreateOneWithoutUserTutorialsInput {
  create?: UserCreateWithoutUserTutorialsInput;
  connect?: UserWhereUniqueInput;
}

export interface UserSubscriptionWhereInput {
  mutation_in?: MutationType[] | MutationType;
  updatedFields_contains?: String;
  updatedFields_contains_every?: String[] | String;
  updatedFields_contains_some?: String[] | String;
  node?: UserWhereInput;
  AND?: UserSubscriptionWhereInput[] | UserSubscriptionWhereInput;
  OR?: UserSubscriptionWhereInput[] | UserSubscriptionWhereInput;
  NOT?: UserSubscriptionWhereInput[] | UserSubscriptionWhereInput;
}

export interface UserCreateWithoutUserTutorialsInput {
  name: String;
  email?: String;
  githubHandle: String;
  githubUserId: String;
  avatarUrl?: String;
  bio?: String;
  contributor?: Boolean;
  expertise?: String;
}

export interface UserTutorialUpdateManyMutationInput {
  upvoted?: Boolean;
  bookmarked?: Boolean;
  currentChapter?: Int;
}

export interface TutorialUpdateInput {
  name?: String;
  gatsbyID?: String;
  numberofChapters?: Int;
  numberofStudents?: Int;
  upvotes?: Int;
  userTutorials?: UserTutorialUpdateManyWithoutTutorialInput;
}

export interface UserTutorialCreateInput {
  user?: UserCreateOneWithoutUserTutorialsInput;
  tutorial?: TutorialCreateOneWithoutUserTutorialsInput;
  upvoted?: Boolean;
  bookmarked?: Boolean;
  currentChapter?: Int;
}

export interface UserTutorialUpdateManyWithoutTutorialInput {
  create?:
    | UserTutorialCreateWithoutTutorialInput[]
    | UserTutorialCreateWithoutTutorialInput;
  delete?: UserTutorialWhereUniqueInput[] | UserTutorialWhereUniqueInput;
  connect?: UserTutorialWhereUniqueInput[] | UserTutorialWhereUniqueInput;
  disconnect?: UserTutorialWhereUniqueInput[] | UserTutorialWhereUniqueInput;
  update?:
    | UserTutorialUpdateWithWhereUniqueWithoutTutorialInput[]
    | UserTutorialUpdateWithWhereUniqueWithoutTutorialInput;
  upsert?:
    | UserTutorialUpsertWithWhereUniqueWithoutTutorialInput[]
    | UserTutorialUpsertWithWhereUniqueWithoutTutorialInput;
  deleteMany?: UserTutorialScalarWhereInput[] | UserTutorialScalarWhereInput;
  updateMany?:
    | UserTutorialUpdateManyWithWhereNestedInput[]
    | UserTutorialUpdateManyWithWhereNestedInput;
}

export interface UserTutorialUpsertWithWhereUniqueWithoutUserInput {
  where: UserTutorialWhereUniqueInput;
  update: UserTutorialUpdateWithoutUserDataInput;
  create: UserTutorialCreateWithoutUserInput;
}

export interface UserTutorialUpdateWithWhereUniqueWithoutTutorialInput {
  where: UserTutorialWhereUniqueInput;
  data: UserTutorialUpdateWithoutTutorialDataInput;
}

export interface TutorialUpsertWithoutUserTutorialsInput {
  update: TutorialUpdateWithoutUserTutorialsDataInput;
  create: TutorialCreateWithoutUserTutorialsInput;
}

export interface UserTutorialUpdateWithoutTutorialDataInput {
  user?: UserUpdateOneWithoutUserTutorialsInput;
  upvoted?: Boolean;
  bookmarked?: Boolean;
  currentChapter?: Int;
}

export interface TutorialUpdateOneWithoutUserTutorialsInput {
  create?: TutorialCreateWithoutUserTutorialsInput;
  update?: TutorialUpdateWithoutUserTutorialsDataInput;
  upsert?: TutorialUpsertWithoutUserTutorialsInput;
  delete?: Boolean;
  disconnect?: Boolean;
  connect?: TutorialWhereUniqueInput;
}

export interface TutorialCreateWithoutUserTutorialsInput {
  name: String;
  gatsbyID: String;
  numberofChapters: Int;
  numberofStudents?: Int;
  upvotes?: Int;
}

export type UserTutorialWhereUniqueInput = AtLeastOne<{
  id: ID_Input;
}>;

export interface UserUpdateWithoutUserTutorialsDataInput {
  name?: String;
  email?: String;
  githubHandle?: String;
  githubUserId?: String;
  avatarUrl?: String;
  bio?: String;
  contributor?: Boolean;
  expertise?: String;
}

export interface UserTutorialUpdateManyWithoutUserInput {
  create?:
    | UserTutorialCreateWithoutUserInput[]
    | UserTutorialCreateWithoutUserInput;
  delete?: UserTutorialWhereUniqueInput[] | UserTutorialWhereUniqueInput;
  connect?: UserTutorialWhereUniqueInput[] | UserTutorialWhereUniqueInput;
  disconnect?: UserTutorialWhereUniqueInput[] | UserTutorialWhereUniqueInput;
  update?:
    | UserTutorialUpdateWithWhereUniqueWithoutUserInput[]
    | UserTutorialUpdateWithWhereUniqueWithoutUserInput;
  upsert?:
    | UserTutorialUpsertWithWhereUniqueWithoutUserInput[]
    | UserTutorialUpsertWithWhereUniqueWithoutUserInput;
  deleteMany?: UserTutorialScalarWhereInput[] | UserTutorialScalarWhereInput;
  updateMany?:
    | UserTutorialUpdateManyWithWhereNestedInput[]
    | UserTutorialUpdateManyWithWhereNestedInput;
}

export interface UserUpsertWithoutUserTutorialsInput {
  update: UserUpdateWithoutUserTutorialsDataInput;
  create: UserCreateWithoutUserTutorialsInput;
}

export interface UserTutorialSubscriptionWhereInput {
  mutation_in?: MutationType[] | MutationType;
  updatedFields_contains?: String;
  updatedFields_contains_every?: String[] | String;
  updatedFields_contains_some?: String[] | String;
  node?: UserTutorialWhereInput;
  AND?:
    | UserTutorialSubscriptionWhereInput[]
    | UserTutorialSubscriptionWhereInput;
  OR?:
    | UserTutorialSubscriptionWhereInput[]
    | UserTutorialSubscriptionWhereInput;
  NOT?:
    | UserTutorialSubscriptionWhereInput[]
    | UserTutorialSubscriptionWhereInput;
}

export interface UserWhereInput {
  id?: ID_Input;
  id_not?: ID_Input;
  id_in?: ID_Input[] | ID_Input;
  id_not_in?: ID_Input[] | ID_Input;
  id_lt?: ID_Input;
  id_lte?: ID_Input;
  id_gt?: ID_Input;
  id_gte?: ID_Input;
  id_contains?: ID_Input;
  id_not_contains?: ID_Input;
  id_starts_with?: ID_Input;
  id_not_starts_with?: ID_Input;
  id_ends_with?: ID_Input;
  id_not_ends_with?: ID_Input;
  createdAt?: DateTimeInput;
  createdAt_not?: DateTimeInput;
  createdAt_in?: DateTimeInput[] | DateTimeInput;
  createdAt_not_in?: DateTimeInput[] | DateTimeInput;
  createdAt_lt?: DateTimeInput;
  createdAt_lte?: DateTimeInput;
  createdAt_gt?: DateTimeInput;
  createdAt_gte?: DateTimeInput;
  updatedAt?: DateTimeInput;
  updatedAt_not?: DateTimeInput;
  updatedAt_in?: DateTimeInput[] | DateTimeInput;
  updatedAt_not_in?: DateTimeInput[] | DateTimeInput;
  updatedAt_lt?: DateTimeInput;
  updatedAt_lte?: DateTimeInput;
  updatedAt_gt?: DateTimeInput;
  updatedAt_gte?: DateTimeInput;
  name?: String;
  name_not?: String;
  name_in?: String[] | String;
  name_not_in?: String[] | String;
  name_lt?: String;
  name_lte?: String;
  name_gt?: String;
  name_gte?: String;
  name_contains?: String;
  name_not_contains?: String;
  name_starts_with?: String;
  name_not_starts_with?: String;
  name_ends_with?: String;
  name_not_ends_with?: String;
  email?: String;
  email_not?: String;
  email_in?: String[] | String;
  email_not_in?: String[] | String;
  email_lt?: String;
  email_lte?: String;
  email_gt?: String;
  email_gte?: String;
  email_contains?: String;
  email_not_contains?: String;
  email_starts_with?: String;
  email_not_starts_with?: String;
  email_ends_with?: String;
  email_not_ends_with?: String;
  githubHandle?: String;
  githubHandle_not?: String;
  githubHandle_in?: String[] | String;
  githubHandle_not_in?: String[] | String;
  githubHandle_lt?: String;
  githubHandle_lte?: String;
  githubHandle_gt?: String;
  githubHandle_gte?: String;
  githubHandle_contains?: String;
  githubHandle_not_contains?: String;
  githubHandle_starts_with?: String;
  githubHandle_not_starts_with?: String;
  githubHandle_ends_with?: String;
  githubHandle_not_ends_with?: String;
  githubUserId?: String;
  githubUserId_not?: String;
  githubUserId_in?: String[] | String;
  githubUserId_not_in?: String[] | String;
  githubUserId_lt?: String;
  githubUserId_lte?: String;
  githubUserId_gt?: String;
  githubUserId_gte?: String;
  githubUserId_contains?: String;
  githubUserId_not_contains?: String;
  githubUserId_starts_with?: String;
  githubUserId_not_starts_with?: String;
  githubUserId_ends_with?: String;
  githubUserId_not_ends_with?: String;
  avatarUrl?: String;
  avatarUrl_not?: String;
  avatarUrl_in?: String[] | String;
  avatarUrl_not_in?: String[] | String;
  avatarUrl_lt?: String;
  avatarUrl_lte?: String;
  avatarUrl_gt?: String;
  avatarUrl_gte?: String;
  avatarUrl_contains?: String;
  avatarUrl_not_contains?: String;
  avatarUrl_starts_with?: String;
  avatarUrl_not_starts_with?: String;
  avatarUrl_ends_with?: String;
  avatarUrl_not_ends_with?: String;
  bio?: String;
  bio_not?: String;
  bio_in?: String[] | String;
  bio_not_in?: String[] | String;
  bio_lt?: String;
  bio_lte?: String;
  bio_gt?: String;
  bio_gte?: String;
  bio_contains?: String;
  bio_not_contains?: String;
  bio_starts_with?: String;
  bio_not_starts_with?: String;
  bio_ends_with?: String;
  bio_not_ends_with?: String;
  contributor?: Boolean;
  contributor_not?: Boolean;
  expertise?: String;
  expertise_not?: String;
  expertise_in?: String[] | String;
  expertise_not_in?: String[] | String;
  expertise_lt?: String;
  expertise_lte?: String;
  expertise_gt?: String;
  expertise_gte?: String;
  expertise_contains?: String;
  expertise_not_contains?: String;
  expertise_starts_with?: String;
  expertise_not_starts_with?: String;
  expertise_ends_with?: String;
  expertise_not_ends_with?: String;
  userTutorials_every?: UserTutorialWhereInput;
  userTutorials_some?: UserTutorialWhereInput;
  userTutorials_none?: UserTutorialWhereInput;
  AND?: UserWhereInput[] | UserWhereInput;
  OR?: UserWhereInput[] | UserWhereInput;
  NOT?: UserWhereInput[] | UserWhereInput;
}

export interface UserTutorialUpdateInput {
  user?: UserUpdateOneWithoutUserTutorialsInput;
  tutorial?: TutorialUpdateOneWithoutUserTutorialsInput;
  upvoted?: Boolean;
  bookmarked?: Boolean;
  currentChapter?: Int;
}

export interface TutorialWhereInput {
  id?: ID_Input;
  id_not?: ID_Input;
  id_in?: ID_Input[] | ID_Input;
  id_not_in?: ID_Input[] | ID_Input;
  id_lt?: ID_Input;
  id_lte?: ID_Input;
  id_gt?: ID_Input;
  id_gte?: ID_Input;
  id_contains?: ID_Input;
  id_not_contains?: ID_Input;
  id_starts_with?: ID_Input;
  id_not_starts_with?: ID_Input;
  id_ends_with?: ID_Input;
  id_not_ends_with?: ID_Input;
  createdAt?: DateTimeInput;
  createdAt_not?: DateTimeInput;
  createdAt_in?: DateTimeInput[] | DateTimeInput;
  createdAt_not_in?: DateTimeInput[] | DateTimeInput;
  createdAt_lt?: DateTimeInput;
  createdAt_lte?: DateTimeInput;
  createdAt_gt?: DateTimeInput;
  createdAt_gte?: DateTimeInput;
  updatedAt?: DateTimeInput;
  updatedAt_not?: DateTimeInput;
  updatedAt_in?: DateTimeInput[] | DateTimeInput;
  updatedAt_not_in?: DateTimeInput[] | DateTimeInput;
  updatedAt_lt?: DateTimeInput;
  updatedAt_lte?: DateTimeInput;
  updatedAt_gt?: DateTimeInput;
  updatedAt_gte?: DateTimeInput;
  name?: String;
  name_not?: String;
  name_in?: String[] | String;
  name_not_in?: String[] | String;
  name_lt?: String;
  name_lte?: String;
  name_gt?: String;
  name_gte?: String;
  name_contains?: String;
  name_not_contains?: String;
  name_starts_with?: String;
  name_not_starts_with?: String;
  name_ends_with?: String;
  name_not_ends_with?: String;
  gatsbyID?: String;
  gatsbyID_not?: String;
  gatsbyID_in?: String[] | String;
  gatsbyID_not_in?: String[] | String;
  gatsbyID_lt?: String;
  gatsbyID_lte?: String;
  gatsbyID_gt?: String;
  gatsbyID_gte?: String;
  gatsbyID_contains?: String;
  gatsbyID_not_contains?: String;
  gatsbyID_starts_with?: String;
  gatsbyID_not_starts_with?: String;
  gatsbyID_ends_with?: String;
  gatsbyID_not_ends_with?: String;
  numberofChapters?: Int;
  numberofChapters_not?: Int;
  numberofChapters_in?: Int[] | Int;
  numberofChapters_not_in?: Int[] | Int;
  numberofChapters_lt?: Int;
  numberofChapters_lte?: Int;
  numberofChapters_gt?: Int;
  numberofChapters_gte?: Int;
  numberofStudents?: Int;
  numberofStudents_not?: Int;
  numberofStudents_in?: Int[] | Int;
  numberofStudents_not_in?: Int[] | Int;
  numberofStudents_lt?: Int;
  numberofStudents_lte?: Int;
  numberofStudents_gt?: Int;
  numberofStudents_gte?: Int;
  upvotes?: Int;
  upvotes_not?: Int;
  upvotes_in?: Int[] | Int;
  upvotes_not_in?: Int[] | Int;
  upvotes_lt?: Int;
  upvotes_lte?: Int;
  upvotes_gt?: Int;
  upvotes_gte?: Int;
  userTutorials_every?: UserTutorialWhereInput;
  userTutorials_some?: UserTutorialWhereInput;
  userTutorials_none?: UserTutorialWhereInput;
  AND?: TutorialWhereInput[] | TutorialWhereInput;
  OR?: TutorialWhereInput[] | TutorialWhereInput;
  NOT?: TutorialWhereInput[] | TutorialWhereInput;
}

export type UserWhereUniqueInput = AtLeastOne<{
  id: ID_Input;
  email?: String;
  githubHandle?: String;
  githubUserId?: String;
  expertise?: String;
}>;

export interface UserTutorialUpdateManyWithWhereNestedInput {
  where: UserTutorialScalarWhereInput;
  data: UserTutorialUpdateManyDataInput;
}

export interface UserTutorialUpdateWithoutUserDataInput {
  tutorial?: TutorialUpdateOneWithoutUserTutorialsInput;
  upvoted?: Boolean;
  bookmarked?: Boolean;
  currentChapter?: Int;
}

export interface UserTutorialUpdateManyDataInput {
  upvoted?: Boolean;
  bookmarked?: Boolean;
  currentChapter?: Int;
}

export interface UserUpdateInput {
  name?: String;
  email?: String;
  githubHandle?: String;
  githubUserId?: String;
  avatarUrl?: String;
  bio?: String;
  contributor?: Boolean;
  expertise?: String;
  userTutorials?: UserTutorialUpdateManyWithoutUserInput;
}

export interface UserCreateInput {
  name: String;
  email?: String;
  githubHandle: String;
  githubUserId: String;
  avatarUrl?: String;
  bio?: String;
  contributor?: Boolean;
  expertise?: String;
  userTutorials?: UserTutorialCreateManyWithoutUserInput;
}

export interface UserTutorialCreateWithoutUserInput {
  tutorial?: TutorialCreateOneWithoutUserTutorialsInput;
  upvoted?: Boolean;
  bookmarked?: Boolean;
  currentChapter?: Int;
}

export interface TutorialCreateOneWithoutUserTutorialsInput {
  create?: TutorialCreateWithoutUserTutorialsInput;
  connect?: TutorialWhereUniqueInput;
}

export interface TutorialUpdateManyMutationInput {
  name?: String;
  gatsbyID?: String;
  numberofChapters?: Int;
  numberofStudents?: Int;
  upvotes?: Int;
}

export interface TutorialCreateInput {
  name: String;
  gatsbyID: String;
  numberofChapters: Int;
  numberofStudents?: Int;
  upvotes?: Int;
  userTutorials?: UserTutorialCreateManyWithoutTutorialInput;
}

export interface UserTutorialUpdateWithWhereUniqueWithoutUserInput {
  where: UserTutorialWhereUniqueInput;
  data: UserTutorialUpdateWithoutUserDataInput;
}

export interface TutorialUpdateWithoutUserTutorialsDataInput {
  name?: String;
  gatsbyID?: String;
  numberofChapters?: Int;
  numberofStudents?: Int;
  upvotes?: Int;
}

export interface UserUpdateManyMutationInput {
  name?: String;
  email?: String;
  githubHandle?: String;
  githubUserId?: String;
  avatarUrl?: String;
  bio?: String;
  contributor?: Boolean;
  expertise?: String;
}

export interface TutorialSubscriptionWhereInput {
  mutation_in?: MutationType[] | MutationType;
  updatedFields_contains?: String;
  updatedFields_contains_every?: String[] | String;
  updatedFields_contains_some?: String[] | String;
  node?: TutorialWhereInput;
  AND?: TutorialSubscriptionWhereInput[] | TutorialSubscriptionWhereInput;
  OR?: TutorialSubscriptionWhereInput[] | TutorialSubscriptionWhereInput;
  NOT?: TutorialSubscriptionWhereInput[] | TutorialSubscriptionWhereInput;
}

export interface NodeNode {
  id: ID_Output;
}

export interface UserTutorialPreviousValues {
  id: ID_Output;
  createdAt: DateTimeOutput;
  updatedAt: DateTimeOutput;
  upvoted?: Boolean;
  bookmarked?: Boolean;
  currentChapter?: Int;
}

export interface UserTutorialPreviousValuesPromise
  extends Promise<UserTutorialPreviousValues>,
    Fragmentable {
  id: () => Promise<ID_Output>;
  createdAt: () => Promise<DateTimeOutput>;
  updatedAt: () => Promise<DateTimeOutput>;
  upvoted: () => Promise<Boolean>;
  bookmarked: () => Promise<Boolean>;
  currentChapter: () => Promise<Int>;
}

export interface UserTutorialPreviousValuesSubscription
  extends Promise<AsyncIterator<UserTutorialPreviousValues>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  createdAt: () => Promise<AsyncIterator<DateTimeOutput>>;
  updatedAt: () => Promise<AsyncIterator<DateTimeOutput>>;
  upvoted: () => Promise<AsyncIterator<Boolean>>;
  bookmarked: () => Promise<AsyncIterator<Boolean>>;
  currentChapter: () => Promise<AsyncIterator<Int>>;
}

export interface AggregateTutorial {
  count: Int;
}

export interface AggregateTutorialPromise
  extends Promise<AggregateTutorial>,
    Fragmentable {
  count: () => Promise<Int>;
}

export interface AggregateTutorialSubscription
  extends Promise<AsyncIterator<AggregateTutorial>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Int>>;
}

export interface UserTutorial {
  id: ID_Output;
  createdAt: DateTimeOutput;
  updatedAt: DateTimeOutput;
  upvoted?: Boolean;
  bookmarked?: Boolean;
  currentChapter?: Int;
}

export interface UserTutorialPromise
  extends Promise<UserTutorial>,
    Fragmentable {
  id: () => Promise<ID_Output>;
  createdAt: () => Promise<DateTimeOutput>;
  updatedAt: () => Promise<DateTimeOutput>;
  user: <T = UserPromise>() => T;
  tutorial: <T = TutorialPromise>() => T;
  upvoted: () => Promise<Boolean>;
  bookmarked: () => Promise<Boolean>;
  currentChapter: () => Promise<Int>;
}

export interface UserTutorialSubscription
  extends Promise<AsyncIterator<UserTutorial>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  createdAt: () => Promise<AsyncIterator<DateTimeOutput>>;
  updatedAt: () => Promise<AsyncIterator<DateTimeOutput>>;
  user: <T = UserSubscription>() => T;
  tutorial: <T = TutorialSubscription>() => T;
  upvoted: () => Promise<AsyncIterator<Boolean>>;
  bookmarked: () => Promise<AsyncIterator<Boolean>>;
  currentChapter: () => Promise<AsyncIterator<Int>>;
}

export interface TutorialEdge {
  node: Tutorial;
  cursor: String;
}

export interface TutorialEdgePromise
  extends Promise<TutorialEdge>,
    Fragmentable {
  node: <T = TutorialPromise>() => T;
  cursor: () => Promise<String>;
}

export interface TutorialEdgeSubscription
  extends Promise<AsyncIterator<TutorialEdge>>,
    Fragmentable {
  node: <T = TutorialSubscription>() => T;
  cursor: () => Promise<AsyncIterator<String>>;
}

export interface PageInfo {
  hasNextPage: Boolean;
  hasPreviousPage: Boolean;
  startCursor?: String;
  endCursor?: String;
}

export interface PageInfoPromise extends Promise<PageInfo>, Fragmentable {
  hasNextPage: () => Promise<Boolean>;
  hasPreviousPage: () => Promise<Boolean>;
  startCursor: () => Promise<String>;
  endCursor: () => Promise<String>;
}

export interface PageInfoSubscription
  extends Promise<AsyncIterator<PageInfo>>,
    Fragmentable {
  hasNextPage: () => Promise<AsyncIterator<Boolean>>;
  hasPreviousPage: () => Promise<AsyncIterator<Boolean>>;
  startCursor: () => Promise<AsyncIterator<String>>;
  endCursor: () => Promise<AsyncIterator<String>>;
}

export interface BatchPayload {
  count: Long;
}

export interface BatchPayloadPromise
  extends Promise<BatchPayload>,
    Fragmentable {
  count: () => Promise<Long>;
}

export interface BatchPayloadSubscription
  extends Promise<AsyncIterator<BatchPayload>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Long>>;
}

export interface AggregateUserTutorial {
  count: Int;
}

export interface AggregateUserTutorialPromise
  extends Promise<AggregateUserTutorial>,
    Fragmentable {
  count: () => Promise<Int>;
}

export interface AggregateUserTutorialSubscription
  extends Promise<AsyncIterator<AggregateUserTutorial>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Int>>;
}

export interface TutorialConnection {
  pageInfo: PageInfo;
  edges: TutorialEdge[];
}

export interface TutorialConnectionPromise
  extends Promise<TutorialConnection>,
    Fragmentable {
  pageInfo: <T = PageInfoPromise>() => T;
  edges: <T = FragmentableArray<TutorialEdge>>() => T;
  aggregate: <T = AggregateTutorialPromise>() => T;
}

export interface TutorialConnectionSubscription
  extends Promise<AsyncIterator<TutorialConnection>>,
    Fragmentable {
  pageInfo: <T = PageInfoSubscription>() => T;
  edges: <T = Promise<AsyncIterator<TutorialEdgeSubscription>>>() => T;
  aggregate: <T = AggregateTutorialSubscription>() => T;
}

export interface UserTutorialConnection {
  pageInfo: PageInfo;
  edges: UserTutorialEdge[];
}

export interface UserTutorialConnectionPromise
  extends Promise<UserTutorialConnection>,
    Fragmentable {
  pageInfo: <T = PageInfoPromise>() => T;
  edges: <T = FragmentableArray<UserTutorialEdge>>() => T;
  aggregate: <T = AggregateUserTutorialPromise>() => T;
}

export interface UserTutorialConnectionSubscription
  extends Promise<AsyncIterator<UserTutorialConnection>>,
    Fragmentable {
  pageInfo: <T = PageInfoSubscription>() => T;
  edges: <T = Promise<AsyncIterator<UserTutorialEdgeSubscription>>>() => T;
  aggregate: <T = AggregateUserTutorialSubscription>() => T;
}

export interface UserPreviousValues {
  id: ID_Output;
  createdAt: DateTimeOutput;
  updatedAt: DateTimeOutput;
  name: String;
  email?: String;
  githubHandle: String;
  githubUserId: String;
  avatarUrl?: String;
  bio?: String;
  contributor?: Boolean;
  expertise?: String;
}

export interface UserPreviousValuesPromise
  extends Promise<UserPreviousValues>,
    Fragmentable {
  id: () => Promise<ID_Output>;
  createdAt: () => Promise<DateTimeOutput>;
  updatedAt: () => Promise<DateTimeOutput>;
  name: () => Promise<String>;
  email: () => Promise<String>;
  githubHandle: () => Promise<String>;
  githubUserId: () => Promise<String>;
  avatarUrl: () => Promise<String>;
  bio: () => Promise<String>;
  contributor: () => Promise<Boolean>;
  expertise: () => Promise<String>;
}

export interface UserPreviousValuesSubscription
  extends Promise<AsyncIterator<UserPreviousValues>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  createdAt: () => Promise<AsyncIterator<DateTimeOutput>>;
  updatedAt: () => Promise<AsyncIterator<DateTimeOutput>>;
  name: () => Promise<AsyncIterator<String>>;
  email: () => Promise<AsyncIterator<String>>;
  githubHandle: () => Promise<AsyncIterator<String>>;
  githubUserId: () => Promise<AsyncIterator<String>>;
  avatarUrl: () => Promise<AsyncIterator<String>>;
  bio: () => Promise<AsyncIterator<String>>;
  contributor: () => Promise<AsyncIterator<Boolean>>;
  expertise: () => Promise<AsyncIterator<String>>;
}

export interface UserEdge {
  node: User;
  cursor: String;
}

export interface UserEdgePromise extends Promise<UserEdge>, Fragmentable {
  node: <T = UserPromise>() => T;
  cursor: () => Promise<String>;
}

export interface UserEdgeSubscription
  extends Promise<AsyncIterator<UserEdge>>,
    Fragmentable {
  node: <T = UserSubscription>() => T;
  cursor: () => Promise<AsyncIterator<String>>;
}

export interface Tutorial {
  id: ID_Output;
  createdAt: DateTimeOutput;
  updatedAt: DateTimeOutput;
  name: String;
  gatsbyID: String;
  numberofChapters: Int;
  numberofStudents: Int;
  upvotes: Int;
}

export interface TutorialPromise extends Promise<Tutorial>, Fragmentable {
  id: () => Promise<ID_Output>;
  createdAt: () => Promise<DateTimeOutput>;
  updatedAt: () => Promise<DateTimeOutput>;
  name: () => Promise<String>;
  gatsbyID: () => Promise<String>;
  numberofChapters: () => Promise<Int>;
  numberofStudents: () => Promise<Int>;
  upvotes: () => Promise<Int>;
  userTutorials: <T = FragmentableArray<UserTutorial>>(
    args?: {
      where?: UserTutorialWhereInput;
      orderBy?: UserTutorialOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => T;
}

export interface TutorialSubscription
  extends Promise<AsyncIterator<Tutorial>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  createdAt: () => Promise<AsyncIterator<DateTimeOutput>>;
  updatedAt: () => Promise<AsyncIterator<DateTimeOutput>>;
  name: () => Promise<AsyncIterator<String>>;
  gatsbyID: () => Promise<AsyncIterator<String>>;
  numberofChapters: () => Promise<AsyncIterator<Int>>;
  numberofStudents: () => Promise<AsyncIterator<Int>>;
  upvotes: () => Promise<AsyncIterator<Int>>;
  userTutorials: <T = Promise<AsyncIterator<UserTutorialSubscription>>>(
    args?: {
      where?: UserTutorialWhereInput;
      orderBy?: UserTutorialOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => T;
}

export interface TutorialPreviousValues {
  id: ID_Output;
  createdAt: DateTimeOutput;
  updatedAt: DateTimeOutput;
  name: String;
  gatsbyID: String;
  numberofChapters: Int;
  numberofStudents: Int;
  upvotes: Int;
}

export interface TutorialPreviousValuesPromise
  extends Promise<TutorialPreviousValues>,
    Fragmentable {
  id: () => Promise<ID_Output>;
  createdAt: () => Promise<DateTimeOutput>;
  updatedAt: () => Promise<DateTimeOutput>;
  name: () => Promise<String>;
  gatsbyID: () => Promise<String>;
  numberofChapters: () => Promise<Int>;
  numberofStudents: () => Promise<Int>;
  upvotes: () => Promise<Int>;
}

export interface TutorialPreviousValuesSubscription
  extends Promise<AsyncIterator<TutorialPreviousValues>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  createdAt: () => Promise<AsyncIterator<DateTimeOutput>>;
  updatedAt: () => Promise<AsyncIterator<DateTimeOutput>>;
  name: () => Promise<AsyncIterator<String>>;
  gatsbyID: () => Promise<AsyncIterator<String>>;
  numberofChapters: () => Promise<AsyncIterator<Int>>;
  numberofStudents: () => Promise<AsyncIterator<Int>>;
  upvotes: () => Promise<AsyncIterator<Int>>;
}

export interface TutorialSubscriptionPayload {
  mutation: MutationType;
  node: Tutorial;
  updatedFields: String[];
  previousValues: TutorialPreviousValues;
}

export interface TutorialSubscriptionPayloadPromise
  extends Promise<TutorialSubscriptionPayload>,
    Fragmentable {
  mutation: () => Promise<MutationType>;
  node: <T = TutorialPromise>() => T;
  updatedFields: () => Promise<String[]>;
  previousValues: <T = TutorialPreviousValuesPromise>() => T;
}

export interface TutorialSubscriptionPayloadSubscription
  extends Promise<AsyncIterator<TutorialSubscriptionPayload>>,
    Fragmentable {
  mutation: () => Promise<AsyncIterator<MutationType>>;
  node: <T = TutorialSubscription>() => T;
  updatedFields: () => Promise<AsyncIterator<String[]>>;
  previousValues: <T = TutorialPreviousValuesSubscription>() => T;
}

export interface UserSubscriptionPayload {
  mutation: MutationType;
  node: User;
  updatedFields: String[];
  previousValues: UserPreviousValues;
}

export interface UserSubscriptionPayloadPromise
  extends Promise<UserSubscriptionPayload>,
    Fragmentable {
  mutation: () => Promise<MutationType>;
  node: <T = UserPromise>() => T;
  updatedFields: () => Promise<String[]>;
  previousValues: <T = UserPreviousValuesPromise>() => T;
}

export interface UserSubscriptionPayloadSubscription
  extends Promise<AsyncIterator<UserSubscriptionPayload>>,
    Fragmentable {
  mutation: () => Promise<AsyncIterator<MutationType>>;
  node: <T = UserSubscription>() => T;
  updatedFields: () => Promise<AsyncIterator<String[]>>;
  previousValues: <T = UserPreviousValuesSubscription>() => T;
}

export interface User {
  id: ID_Output;
  createdAt: DateTimeOutput;
  updatedAt: DateTimeOutput;
  name: String;
  email?: String;
  githubHandle: String;
  githubUserId: String;
  avatarUrl?: String;
  bio?: String;
  contributor?: Boolean;
  expertise?: String;
}

export interface UserPromise extends Promise<User>, Fragmentable {
  id: () => Promise<ID_Output>;
  createdAt: () => Promise<DateTimeOutput>;
  updatedAt: () => Promise<DateTimeOutput>;
  name: () => Promise<String>;
  email: () => Promise<String>;
  githubHandle: () => Promise<String>;
  githubUserId: () => Promise<String>;
  avatarUrl: () => Promise<String>;
  bio: () => Promise<String>;
  contributor: () => Promise<Boolean>;
  expertise: () => Promise<String>;
  userTutorials: <T = FragmentableArray<UserTutorial>>(
    args?: {
      where?: UserTutorialWhereInput;
      orderBy?: UserTutorialOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => T;
}

export interface UserSubscription
  extends Promise<AsyncIterator<User>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  createdAt: () => Promise<AsyncIterator<DateTimeOutput>>;
  updatedAt: () => Promise<AsyncIterator<DateTimeOutput>>;
  name: () => Promise<AsyncIterator<String>>;
  email: () => Promise<AsyncIterator<String>>;
  githubHandle: () => Promise<AsyncIterator<String>>;
  githubUserId: () => Promise<AsyncIterator<String>>;
  avatarUrl: () => Promise<AsyncIterator<String>>;
  bio: () => Promise<AsyncIterator<String>>;
  contributor: () => Promise<AsyncIterator<Boolean>>;
  expertise: () => Promise<AsyncIterator<String>>;
  userTutorials: <T = Promise<AsyncIterator<UserTutorialSubscription>>>(
    args?: {
      where?: UserTutorialWhereInput;
      orderBy?: UserTutorialOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => T;
}

export interface UserTutorialSubscriptionPayload {
  mutation: MutationType;
  node: UserTutorial;
  updatedFields: String[];
  previousValues: UserTutorialPreviousValues;
}

export interface UserTutorialSubscriptionPayloadPromise
  extends Promise<UserTutorialSubscriptionPayload>,
    Fragmentable {
  mutation: () => Promise<MutationType>;
  node: <T = UserTutorialPromise>() => T;
  updatedFields: () => Promise<String[]>;
  previousValues: <T = UserTutorialPreviousValuesPromise>() => T;
}

export interface UserTutorialSubscriptionPayloadSubscription
  extends Promise<AsyncIterator<UserTutorialSubscriptionPayload>>,
    Fragmentable {
  mutation: () => Promise<AsyncIterator<MutationType>>;
  node: <T = UserTutorialSubscription>() => T;
  updatedFields: () => Promise<AsyncIterator<String[]>>;
  previousValues: <T = UserTutorialPreviousValuesSubscription>() => T;
}

export interface UserConnection {
  pageInfo: PageInfo;
  edges: UserEdge[];
}

export interface UserConnectionPromise
  extends Promise<UserConnection>,
    Fragmentable {
  pageInfo: <T = PageInfoPromise>() => T;
  edges: <T = FragmentableArray<UserEdge>>() => T;
  aggregate: <T = AggregateUserPromise>() => T;
}

export interface UserConnectionSubscription
  extends Promise<AsyncIterator<UserConnection>>,
    Fragmentable {
  pageInfo: <T = PageInfoSubscription>() => T;
  edges: <T = Promise<AsyncIterator<UserEdgeSubscription>>>() => T;
  aggregate: <T = AggregateUserSubscription>() => T;
}

export interface AggregateUser {
  count: Int;
}

export interface AggregateUserPromise
  extends Promise<AggregateUser>,
    Fragmentable {
  count: () => Promise<Int>;
}

export interface AggregateUserSubscription
  extends Promise<AsyncIterator<AggregateUser>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Int>>;
}

export interface UserTutorialEdge {
  node: UserTutorial;
  cursor: String;
}

export interface UserTutorialEdgePromise
  extends Promise<UserTutorialEdge>,
    Fragmentable {
  node: <T = UserTutorialPromise>() => T;
  cursor: () => Promise<String>;
}

export interface UserTutorialEdgeSubscription
  extends Promise<AsyncIterator<UserTutorialEdge>>,
    Fragmentable {
  node: <T = UserTutorialSubscription>() => T;
  cursor: () => Promise<AsyncIterator<String>>;
}

/*
The `Boolean` scalar type represents `true` or `false`.
*/
export type Boolean = boolean;

export type Long = string;

/*
The `ID` scalar type represents a unique identifier, often used to refetch an object or as key for a cache. The ID type appears in a JSON response as a String; however, it is not intended to be human-readable. When expected as an input type, any string (such as `"4"`) or integer (such as `4`) input value will be accepted as an ID.
*/
export type ID_Input = string | number;
export type ID_Output = string;

/*
The `Int` scalar type represents non-fractional signed whole numeric values. Int can represent values between -(2^31) and 2^31 - 1. 
*/
export type Int = number;

/*
DateTime scalar input type, allowing Date
*/
export type DateTimeInput = Date | string;

/*
DateTime scalar output type, which is always a string
*/
export type DateTimeOutput = string;

/*
The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.
*/
export type String = string;

/**
 * Model Metadata
 */

export const models: Model[] = [
  {
    name: "Tutorial",
    embedded: false
  },
  {
    name: "User",
    embedded: false
  },
  {
    name: "UserTutorial",
    embedded: false
  }
];

/**
 * Type Defs
 */

export const Prisma = makePrismaClientClass<ClientConstructor<Prisma>>({
  typeDefs,
  models,
  endpoint: `https://howtographql-prod_howtographql-internal.prisma.sh/howtographql/dev`
});
export const prisma = new Prisma();
