/**
 * This file was automatically generated by Nexus 0.11.3
 * Do not make changes to this file directly
 */

import * as ctx from "../src/context"
import * as prisma from "./prisma-client/index"


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  PostWhereInput: { // input type
    AND?: NexusGenInputs['PostWhereInput'][] | null; // [PostWhereInput!]
    author?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    content?: string | null; // String
    content_contains?: string | null; // String
    content_ends_with?: string | null; // String
    content_gt?: string | null; // String
    content_gte?: string | null; // String
    content_in?: string[] | null; // [String!]
    content_lt?: string | null; // String
    content_lte?: string | null; // String
    content_not?: string | null; // String
    content_not_contains?: string | null; // String
    content_not_ends_with?: string | null; // String
    content_not_in?: string[] | null; // [String!]
    content_not_starts_with?: string | null; // String
    content_starts_with?: string | null; // String
    id?: string | null; // ID
    id_contains?: string | null; // ID
    id_ends_with?: string | null; // ID
    id_gt?: string | null; // ID
    id_gte?: string | null; // ID
    id_in?: string[] | null; // [ID!]
    id_lt?: string | null; // ID
    id_lte?: string | null; // ID
    id_not?: string | null; // ID
    id_not_contains?: string | null; // ID
    id_not_ends_with?: string | null; // ID
    id_not_in?: string[] | null; // [ID!]
    id_not_starts_with?: string | null; // ID
    id_starts_with?: string | null; // ID
    NOT?: NexusGenInputs['PostWhereInput'][] | null; // [PostWhereInput!]
    OR?: NexusGenInputs['PostWhereInput'][] | null; // [PostWhereInput!]
    published?: boolean | null; // Boolean
    published_not?: boolean | null; // Boolean
    title?: string | null; // String
    title_contains?: string | null; // String
    title_ends_with?: string | null; // String
    title_gt?: string | null; // String
    title_gte?: string | null; // String
    title_in?: string[] | null; // [String!]
    title_lt?: string | null; // String
    title_lte?: string | null; // String
    title_not?: string | null; // String
    title_not_contains?: string | null; // String
    title_not_ends_with?: string | null; // String
    title_not_in?: string[] | null; // [String!]
    title_not_starts_with?: string | null; // String
    title_starts_with?: string | null; // String
  }
  UserWhereInput: { // input type
    AND?: NexusGenInputs['UserWhereInput'][] | null; // [UserWhereInput!]
    avatarUrl?: string | null; // String
    avatarUrl_contains?: string | null; // String
    avatarUrl_ends_with?: string | null; // String
    avatarUrl_gt?: string | null; // String
    avatarUrl_gte?: string | null; // String
    avatarUrl_in?: string[] | null; // [String!]
    avatarUrl_lt?: string | null; // String
    avatarUrl_lte?: string | null; // String
    avatarUrl_not?: string | null; // String
    avatarUrl_not_contains?: string | null; // String
    avatarUrl_not_ends_with?: string | null; // String
    avatarUrl_not_in?: string[] | null; // [String!]
    avatarUrl_not_starts_with?: string | null; // String
    avatarUrl_starts_with?: string | null; // String
    bio?: string | null; // String
    bio_contains?: string | null; // String
    bio_ends_with?: string | null; // String
    bio_gt?: string | null; // String
    bio_gte?: string | null; // String
    bio_in?: string[] | null; // [String!]
    bio_lt?: string | null; // String
    bio_lte?: string | null; // String
    bio_not?: string | null; // String
    bio_not_contains?: string | null; // String
    bio_not_ends_with?: string | null; // String
    bio_not_in?: string[] | null; // [String!]
    bio_not_starts_with?: string | null; // String
    bio_starts_with?: string | null; // String
    createdAt?: any | null; // DateTime
    createdAt_gt?: any | null; // DateTime
    createdAt_gte?: any | null; // DateTime
    createdAt_in?: any[] | null; // [DateTime!]
    createdAt_lt?: any | null; // DateTime
    createdAt_lte?: any | null; // DateTime
    createdAt_not?: any | null; // DateTime
    createdAt_not_in?: any[] | null; // [DateTime!]
    email?: string | null; // String
    email_contains?: string | null; // String
    email_ends_with?: string | null; // String
    email_gt?: string | null; // String
    email_gte?: string | null; // String
    email_in?: string[] | null; // [String!]
    email_lt?: string | null; // String
    email_lte?: string | null; // String
    email_not?: string | null; // String
    email_not_contains?: string | null; // String
    email_not_ends_with?: string | null; // String
    email_not_in?: string[] | null; // [String!]
    email_not_starts_with?: string | null; // String
    email_starts_with?: string | null; // String
    githubHandle?: string | null; // String
    githubHandle_contains?: string | null; // String
    githubHandle_ends_with?: string | null; // String
    githubHandle_gt?: string | null; // String
    githubHandle_gte?: string | null; // String
    githubHandle_in?: string[] | null; // [String!]
    githubHandle_lt?: string | null; // String
    githubHandle_lte?: string | null; // String
    githubHandle_not?: string | null; // String
    githubHandle_not_contains?: string | null; // String
    githubHandle_not_ends_with?: string | null; // String
    githubHandle_not_in?: string[] | null; // [String!]
    githubHandle_not_starts_with?: string | null; // String
    githubHandle_starts_with?: string | null; // String
    githubUserId?: string | null; // String
    githubUserId_contains?: string | null; // String
    githubUserId_ends_with?: string | null; // String
    githubUserId_gt?: string | null; // String
    githubUserId_gte?: string | null; // String
    githubUserId_in?: string[] | null; // [String!]
    githubUserId_lt?: string | null; // String
    githubUserId_lte?: string | null; // String
    githubUserId_not?: string | null; // String
    githubUserId_not_contains?: string | null; // String
    githubUserId_not_ends_with?: string | null; // String
    githubUserId_not_in?: string[] | null; // [String!]
    githubUserId_not_starts_with?: string | null; // String
    githubUserId_starts_with?: string | null; // String
    id?: string | null; // ID
    id_contains?: string | null; // ID
    id_ends_with?: string | null; // ID
    id_gt?: string | null; // ID
    id_gte?: string | null; // ID
    id_in?: string[] | null; // [ID!]
    id_lt?: string | null; // ID
    id_lte?: string | null; // ID
    id_not?: string | null; // ID
    id_not_contains?: string | null; // ID
    id_not_ends_with?: string | null; // ID
    id_not_in?: string[] | null; // [ID!]
    id_not_starts_with?: string | null; // ID
    id_starts_with?: string | null; // ID
    name?: string | null; // String
    name_contains?: string | null; // String
    name_ends_with?: string | null; // String
    name_gt?: string | null; // String
    name_gte?: string | null; // String
    name_in?: string[] | null; // [String!]
    name_lt?: string | null; // String
    name_lte?: string | null; // String
    name_not?: string | null; // String
    name_not_contains?: string | null; // String
    name_not_ends_with?: string | null; // String
    name_not_in?: string[] | null; // [String!]
    name_not_starts_with?: string | null; // String
    name_starts_with?: string | null; // String
    NOT?: NexusGenInputs['UserWhereInput'][] | null; // [UserWhereInput!]
    OR?: NexusGenInputs['UserWhereInput'][] | null; // [UserWhereInput!]
    posts_every?: NexusGenInputs['PostWhereInput'] | null; // PostWhereInput
    posts_none?: NexusGenInputs['PostWhereInput'] | null; // PostWhereInput
    posts_some?: NexusGenInputs['PostWhereInput'] | null; // PostWhereInput
    updatedAt?: any | null; // DateTime
    updatedAt_gt?: any | null; // DateTime
    updatedAt_gte?: any | null; // DateTime
    updatedAt_in?: any[] | null; // [DateTime!]
    updatedAt_lt?: any | null; // DateTime
    updatedAt_lte?: any | null; // DateTime
    updatedAt_not?: any | null; // DateTime
    updatedAt_not_in?: any[] | null; // [DateTime!]
  }
}

export interface NexusGenEnums {
  PostOrderByInput: "content_ASC" | "content_DESC" | "createdAt_ASC" | "createdAt_DESC" | "id_ASC" | "id_DESC" | "published_ASC" | "published_DESC" | "title_ASC" | "title_DESC" | "updatedAt_ASC" | "updatedAt_DESC"
}

export interface NexusGenRootTypes {
  AuthenticateUserPayload: { // root type
    token: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  Mutation: {};
  Post: prisma.Post;
  Query: {};
  User: prisma.User;
  Viewer: { // root type
    id: string; // ID!
  }
  String: string;
  Int: number;
  Float: number;
  Boolean: boolean;
  ID: string;
  DateTime: any;
}

export interface NexusGenAllTypes extends NexusGenRootTypes {
  PostWhereInput: NexusGenInputs['PostWhereInput'];
  UserWhereInput: NexusGenInputs['UserWhereInput'];
  PostOrderByInput: NexusGenEnums['PostOrderByInput'];
}

export interface NexusGenFieldTypes {
  AuthenticateUserPayload: { // field return type
    token: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  Mutation: { // field return type
    authenticate: NexusGenRootTypes['AuthenticateUserPayload'] | null; // AuthenticateUserPayload
    createDraft: NexusGenRootTypes['Post']; // Post!
    deletePost: NexusGenRootTypes['Post'] | null; // Post
    publish: NexusGenRootTypes['Post']; // Post!
    signupUser: NexusGenRootTypes['User']; // User!
  }
  Post: { // field return type
    author: NexusGenRootTypes['User']; // User!
    content: string; // String!
    id: string; // ID!
    published: boolean; // Boolean!
    title: string; // String!
  }
  Query: { // field return type
    feed: NexusGenRootTypes['Post'][]; // [Post!]!
    filterPosts: NexusGenRootTypes['Post'][]; // [Post!]!
    viewer: NexusGenRootTypes['Viewer'] | null; // Viewer
  }
  User: { // field return type
    avatarUrl: string | null; // String
    bio: string; // String!
    createdAt: any; // DateTime!
    email: string; // String!
    githubHandle: string; // String!
    githubUserId: string; // String!
    id: string; // ID!
    name: string; // String!
    posts: NexusGenRootTypes['Post'][] | null; // [Post!]
    updatedAt: any; // DateTime!
  }
  Viewer: { // field return type
    id: string; // ID!
    user: NexusGenRootTypes['User']; // User!
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    authenticate: { // args
      githubCode: string; // String!
    }
    createDraft: { // args
      authorEmail: string; // String!
      content: string; // String!
      title: string; // String!
    }
    deletePost: { // args
      id: string; // ID!
    }
    publish: { // args
      id: string; // ID!
    }
    signupUser: { // args
      email: string; // String!
      name: string; // String!
    }
  }
  Query: {
    filterPosts: { // args
      searchString: string; // String!
    }
  }
  User: {
    posts: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenEnums['PostOrderByInput'] | null; // PostOrderByInput
      skip?: number | null; // Int
      where?: NexusGenInputs['PostWhereInput'] | null; // PostWhereInput
    }
  }
}

export interface NexusGenAbstractResolveReturnTypes {
}

export interface NexusGenInheritedFields {}

export type NexusGenObjectNames = "AuthenticateUserPayload" | "Mutation" | "Post" | "Query" | "User" | "Viewer";

export type NexusGenInputNames = "PostWhereInput" | "UserWhereInput";

export type NexusGenEnumNames = "PostOrderByInput";

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = "Boolean" | "DateTime" | "Float" | "ID" | "Int" | "String";

export type NexusGenUnionNames = never;

export interface NexusGenTypes {
  context: ctx.Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  allTypes: NexusGenAllTypes;
  inheritedFields: NexusGenInheritedFields;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractResolveReturn: NexusGenAbstractResolveReturnTypes;
}